name: Expo Android Build

on:
  push:
    branches:
      - master

jobs:
  build-android:
    name: Build Android App with EAS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build Android with EAS
        run: EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} eas build --platform android --profile production --non-interactive --json > android-build.json

      - name: Download AAB file
        id: download_android
        run: |
          apt-get update && apt-get install -y jq curl
          url=$(jq -r '.[0].artifacts.buildUrl' android-build.json)
          echo "Download URL: $url"
          curl -L -o app-android.aab "$url"

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-android
          path: app-android.aab
